### PR TITLE
Pre-process data

### PR DESCRIPTION
**Pull request by Eleonore9**
- Read + transform csv 
- Get houses ids
- Identify new houses
- Create new properties and devices in Hecuba
- Overwrite the mapping file

### CODE REVIEW

**Comment by Eleonore9** [comment]
I have test data locally but excluded it from the commits using the `.gitignore`. Is it Ok?

**Comment by Eleonore9** [comment]
Sorry, but I'm not finished yet!

**Comment by jasebell** [comment]
Yes that should be fine.

**Comment by jasebell** [comment]
lgtm :shipit:

**Pull request merged**
